export const RECIPES = [
  {
    id: 0,
    recipesId: 0,
    name: "Flufy Pancake",
    image: "/images/food-1.jpg",
    featured: true,
    description: 'This card has supporting text below as a natural lead-in to additional content.',
  },
  {
    id: 1,
    recipesId: 1,
    name: "Combo Seafood",
    image: "/images/food-2.jpg",
    featured: false,
    description: 'This card has supporting text below as a natural lead-in to additional content.',
  },
  {
    id: 2,
    recipesId: 2,
    name: "Steaks",
    image: "/images/food-3.jpg",
    featured: false,
    description: 'This card has supporting text below as a natural lead-in to additional content.',
  },
    {
    id: 3,
    recipesId: 3,
    name: "Flufy Pancake",
    image: "/images/food-1.jpg",
    featured: true,
    description: 'This card has supporting text below as a natural lead-in to additional content.',
  },
  {
    id: 4,
    recipesId: 4,
    name: "Combo Seafood",
    image: "/images/food-2.jpg",
    featured: false,
    description: 'This card has supporting text below as a natural lead-in to additional content.',
  },
  {
    id: 5,
    recipesId: 5,
    name: "Steaks",
    image: "/images/food-3.jpg",
    featured: false,
    description: 'This card has supporting text below as a natural lead-in to additional content.',
  },
];
